CREATE TABLE ARTIST (
    ID   INTEGER   PRIMARY KEY AUTOINCREMENT,
    NAME TEXT (50) NOT NULL
                   UNIQUE
);


CREATE TABLE DATE (
    ID    INTEGER     PRIMARY KEY AUTOINCREMENT,
    YEAR  INTEGER (4) NOT NULL,
    MONTH INTEGER (2) NOT NULL,
    DAY   INTEGER (2) NOT NULL
);

CREATE TABLE LISTEN (
    ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    SONG_ID   INTEGER REFERENCES Song (ID) ON DELETE CASCADE
                      NOT NULL,
    DATE_ID   DATE    REFERENCES DATE (ID) ON DELETE CASCADE
                      NOT NULL,
    TIME_ID   INTEGER REFERENCES TIME (ID) ON DELETE CASCADE
                      NOT NULL,
    USER_ID   INTEGER REFERENCES USER (ID) ON DELETE CASCADE
                      NOT NULL,
    ARTIST_ID INTEGER REFERENCES ARTIST (ID) 
                      NOT NULL
);

CREATE TABLE SONG (
    ID        INTEGER    PRIMARY KEY AUTOINCREMENT,
    TITLE     TEXT (150) NOT NULL,
    SONG_ID   TEXT (30)  NOT NULL
                         UNIQUE,
    ARTIST_ID INTEGER    REFERENCES ARTIST (ID) 
);

CREATE TABLE TIME (
    ID     INTEGER     PRIMARY KEY AUTOINCREMENT,
    HOUR   INTEGER (2) NOT NULL,
    MINUTE INTEGER (2) NOT NULL
);


CREATE TABLE USER (
    ID        INTEGER     PRIMARY KEY AUTOINCREMENT,
    USER_F_ID STRING (50) UNIQUE
                          NOT NULL
);


